"""每周刷新两把锁，有真变化就交给调用方出 PR（快照 P1-12 ④ / ENGI-15 ②）。

跑法：

    .venv\\Scripts\\python.exe scripts/tools/recompile_locks.py            # 判 + 写（CI 用）
    .venv\\Scripts\\python.exe scripts/tools/recompile_locks.py --check     # 只问变没变（本地用）

退出码（**与 audit_deps / scan_secrets 同一族 fail-closed 口径**）：

    0 = 锁没变（什么都不写，PR 不该开）
    1 = 锁变了（已写回工作树，差异摘要打在 stdout）
    2 = 跑不了（装不到 pip-compile / 解析失败 / 锁文件不见了）—— **绝不退成 0**：
        "刷不了" 报成 "没变化"，那周就安静地没有依赖更新，而没人知道。

三条判据都来自 2026-10-08 的实测，不是推测：

  1. **本机 pip 配置会污染锁**：这台机的 `pip.ini` 把清华镜像写成 `--index-url`/
     `--trusted-host`，它们会原样进锁（CONTRIBUTING 8.2 那句"刷新后若头部被本机 pip 配置
     写进 --index-url，删掉再提交"说的就是这件事）。手动流程靠人删，自动化不许靠人 ——
     这里用 `PIP_CONFIG_FILE=os.devnull` 把配置整个屏蔽掉，从源头不产生那一两行。
  2. **判"变没变"不能按字节比**：实测在屏蔽配置后重新 compile，174/136 条 pin 一条没变，
     但字节比仍差一行（人手工删掉镜像行时顺带走了 banner 后那个空行）。按字节比的结果是
     **每周都开一张内容为空的 PR**，第三周就没人看了 —— 所以比的是"去掉注释横幅与空行之后
     的结构行"（pin 与其 via 注记）。横幅里那行命令由 pip-compile 自己写，不动它。
  3. **必须在 Windows 上跑**：锁里含 `pywin32`/`pefile` 这类 `sys_platform=='win32'`
     的解析产物（实查 mcp 与 pyinstaller 的 wheel 元数据），Linux runner 上重新解析会得到
     一份结构不同的锁 —— 那不是依赖更新，是换了平台。见 workflow 里 `runs-on: windows-latest`。

输入清单**读 `LOCK_SURFACES`**（一致性尺子 `lockfile parity` 用的同一张表），不在这里抄一份：
两处各写一遍"哪把锁由哪几份 requirements 产出"迟早漂，而漂了的那份正是没人查的那份。
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

from consistency.checks_install import LOCK_SURFACES  # noqa: E402

#: `package==version` 这一行的形状（pip-tools 的输出里 pin 行永不缩进）。
_PIN = re.compile(r"^([A-Za-z0-9._-]+)==(\S+)")


def _structural(text: str) -> list[str]:
    """去掉注释横幅与空行后的结构行（pin 行 + 其 `# via` 注记）。

    `--index-url` / `--trusted-host` 这类"本机 pip 配置漏进锁"的行一并滤掉：它们不是
    依赖信息，而 CONTRIBUTING 8.2 的处置本来就是删掉。横幅（`# This file is autogenerated…`）
    由 pip-compile 自己维护，不进比较。
    """
    out: list[str] = []
    for line in text.splitlines():
        if not line.strip():
            continue
        if line.startswith("--index-url") or line.startswith("--trusted-host"):
            continue
        if line.startswith("#") and not line.startswith("# via") and " #" not in line:
            # pip-tools 的 via 注记是缩进行（`    # via aiohttp`），不是以 '#' 开头的行，
            # 所以以 '#' 开头的只可能是顶部横幅 —— 丢掉。
            continue
        out.append(line.rstrip())
    return out


def _pins(text: str) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in text.splitlines():
        m = _PIN.match(line)
        if m:
            pins[m.group(1).lower()] = m.group(2)
    return pins


def diff_summary(old: str, new: str) -> list[str]:
    """人读的差异清单：新增 / 删除 / 换版。结构行相同就返回空。"""
    a, b = _pins(old), _pins(new)
    lines: list[str] = []
    for name in sorted(set(b) - set(a)):
        lines.append(f"added   {name}=={b[name]}")
    for name in sorted(set(a) - set(b)):
        lines.append(f"removed {name}=={a[name]}")
    for name in sorted(set(a) & set(b)):
        if a[name] != b[name]:
            lines.append(f"changed {name}: {a[name]} -> {b[name]}")
    if not lines and _structural(old) != _structural(new):
        lines.append("changed (annotations only)")
    return lines


def _compile(lock: str, env: dict[str, str]) -> str | None:
    """跑 pip-compile 重新产出这一把锁，返回新内容；跑不了返回 None（调用方按 exit 2 处理）。

    **失败路径必须自己善后**：pip-tools 是直接覆写目标文件的（`writer.py` 里开 `dst` 写，
    没有"临时文件再改名"那一步），所以"跑到一半崩"会在工作树里留下一份**被截断的锁**。
    调用方拿到 None 只会退 2 喊红 —— 红得很正确，锁却已经坏了，而下一次 `pip install -r`
    坏锁的现场是"装不上"，没人会想到是上周那次红弄的。所以每条失败路径都先把进入前的
    字节放回去，再返回 None。成功那条把新内容留在工作树里，交给调用方判与写。
    """
    path = ROOT / lock
    try:
        before = path.read_bytes()
    except OSError:
        print(f"[recompile_locks] {lock}: 读不到原内容，不动它", file=sys.stderr)
        return None
    inputs = sorted(LOCK_SURFACES[lock])
    cmd = [sys.executable, "-m", "piptools", "compile", "--output-file", lock, *inputs]
    try:
        r = subprocess.run(
            cmd,
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=int(os.environ.get("LOCK_REFRESH_TIMEOUT", "3600")),
            env=env,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"[recompile_locks] {lock}: 跑不动（{type(exc).__name__}: {exc}）", file=sys.stderr)
        path.write_bytes(before)
        return None
    if r.returncode != 0:
        print(f"[recompile_locks] {lock}: pip-compile 退 {r.returncode}", file=sys.stderr)
        print((r.stderr or r.stdout)[-800:], file=sys.stderr)
        path.write_bytes(before)
        return None
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"[recompile_locks] {lock}: 读不回来（{exc}）", file=sys.stderr)
        path.write_bytes(before)
        return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="只判有没有变（不写回工作树）；退出码照旧 0/1/2",
    )
    args = ap.parse_args()

    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    # 探测 pip-tools 可用性的这一步自己也不能抛：`shutil.which` 找不到 `pip-compile`
    # 可执行文件（Windows 上很常见，只有模块入口）时要退到 `python -m piptools`，
    # 而那一次 `subprocess.run` 若裸奔（解释器路径有问题、权限、被杀），异常会一路冲出
    # `main()` —— 进程退成 1，而**调用方的契约里 1 = "锁变了"**：CI 会拿着一次
    # 根本没验过的解析结果去开 PR。fail-closed 的口径要求"跑不动"只能是 2。
    if shutil.which("pip-compile") is None:
        try:
            probe = subprocess.run(
                [sys.executable, "-m", "piptools", "--help"],
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except (OSError, subprocess.SubprocessError) as exc:
            print(
                f"[recompile_locks] 探不到 pip-tools（{type(exc).__name__}: {exc}），"
                "按红线当红（exit=2）",
                file=sys.stderr,
            )
            return 2
        if probe.returncode != 0:
            print("[recompile_locks] 装不到 pip-tools，按红线当红（exit=2）", file=sys.stderr)
            return 2

    # 本机 pip 配置（镜像源 / 代理）不许参与锁的生成 —— 见模块 docstring 第 1 条。
    env = {**os.environ, "PIP_CONFIG_FILE": os.devnull}

    changed: list[str] = []
    for lock in sorted(LOCK_SURFACES):
        path = ROOT / lock
        if not path.exists():
            print(f"[recompile_locks] {lock} 不见了 —— 不猜，当红", file=sys.stderr)
            return 2
        before = path.read_text(encoding="utf-8")
        fresh = _compile(lock, env)
        if fresh is None:
            return 2  # fail-closed：刷不了 ≠ 没变化
        if _structural(before) == _structural(fresh):
            # pip-compile 是直接覆写目标文件的，所以"没变化"这条路也得把原内容放回去：
            # 横幅后那个空行的有无属于历史手改的残留（CONTRIBUTING 8.2 删镜像行的副产物），
            # 语义没变而工作树被改脏 —— 一次 no-op 跑出 dirty tree，下一次 diff 就说不清了。
            path.write_text(before, encoding="utf-8", newline="\n")
            print(f"[recompile_locks] {lock}: 依赖未变（结构行一致，pin 一条没动）")
            continue
        summary = diff_summary(before, fresh)
        print(f"[recompile_locks] {lock}: 有变化 ——")
        for line in summary:
            print(f"    {line}")
        if args.check:
            # --check 把原内容放回去：compile 是直接覆写目标文件的，这里等于"看过但没动"
            path.write_text(before, encoding="utf-8", newline="\n")
        else:
            path.write_text(fresh, encoding="utf-8", newline="\n")
        changed.append(lock)

    if not changed:
        return 0
    print(f"[recompile_locks] 改动落在：{', '.join(changed)}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
