"""CHECKS 注册表 —— 断言的**执行顺序**只有这一处。

从前顺序写在 main() 的函数调用里；现在是一张表。新尺子加在这里（并保持顺序：
便宜的、能早红的排前面），包装器只负责跑与汇总。
"""
from __future__ import annotations

from . import checks, checks_install

CHECKS = (
    checks_install.check_pyproject,
    checks_install.check_requirements_scope,
    checks.check_stale_identifiers,
    checks.check_config_contract,
    checks.check_startup_env_documented,
    checks_install.check_dependency_parity,
    checks_install.check_spec_runtime_vs_requirements,
    checks.check_promised_artifacts,
    checks.check_core_no_domain_token,
    checks.check_api_domain_seams,
    checks.check_identity_implicit_reads_are_registered,
    checks.check_audit_action_vocabulary,
    checks.check_session_thread_write_seam,
    checks.check_storage_db_has_no_business_tables,
    checks.check_api_holds_no_sql,
    checks.check_log_channels_unified,
    checks.check_sync_write_ownership,
    checks.check_write_txn_ownership_inventory,
    checks.check_audit_ledger_row_count,
    checks.check_data_root_dirs_gitignored,
    checks.check_ledger_status_states_verdict,
    checks.check_app_icon_frames,
    checks.check_single_text_extractor,
    checks.check_domain_isolation,
    checks.check_safety_prompt,
    checks.check_line_endings,
    checks.check_ps1_encoding,
    checks.check_console_encoding,
    checks.check_readme_quickstart,
    checks.check_readme_headline_numbers,
    checks.check_milestone_alignment,
    checks.check_v1_v2_boundary,
    checks.check_doc_references,
    checks.check_doc_links,
    checks.check_markdown_table_shape,
    checks.check_citation_reachability,
    checks.check_doc_freshness,
    checks.check_audit_index_in_sync,
    checks.check_version_parity,
    checks.check_changelog,
    checks.check_coverage_threshold,
    checks.check_dead_config,
    checks.check_dependency_layering,
    checks.check_env_example_models,
    checks_install.check_installer_scope,
    checks_install.check_lockfile_parity,
    checks_install.check_capability_matrix,
    checks.check_ci_host_python_stdlib_only,
    checks.check_artifact_single_source,
    checks.check_single_source_literals,
    checks.check_local_service_port_single_source,
    checks.check_dangling_write_txns,
    checks.check_shape_migration_ddl,
    checks.check_bundled_copy,
    checks.check_vocabulary,
    checks.check_deploy_env_parity,
    checks.check_role_whitelists_resolve,
    checks.check_us_traceability,
    checks.check_exemplar_leaks_eval_answers,
    checks.report_line_budget,
)
