"""`recompile_locks` 的判据本体（P1-12 ④ / ENGI-15 ② 的周更锁差异 PR）。

这条尺子的**危险不在漏报，在误报**：把"没变化"判成"有变化"，每周开一张内容空洞的 PR，
第三周就没人读了 —— 而"没人读的 PR"比"没有 PR"更坏（它让人以为这件事有人管）。
所以这一族用例全部围绕两个方向：

  * **该闭嘴的时候闭嘴**：横幅/注释/空行的形状差异，pin 一条没动 ⇒ 不许算变化
    （2026-10-08 实测到这正是按字节比会踩的坑：重新 compile 出一份 pin 完全相同、
     只差一个空行的锁）；
  * **该出声的时候出声**：任何一条 pin 动了都必须报，包括只动一位小版本、
    包括新增与删除，也包括"结构行变了但 pin 集合没变"那种注释级变化（降级成
    annotations only，仍算变化，因为 via 注记变了说明依赖图变了）。

不联网：这里测的是比较逻辑与退出码语义，真 compile 那一步在 CI 里跑（本仓的
"测试全部离线"铁律）。
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# 与 build_audit_index 同一手法：按文件加载，绕开 scripts/ 的包结构。
_SCRIPT = ROOT / "scripts" / "tools" / "recompile_locks.py"
_spec = importlib.util.spec_from_file_location("recompile_locks_under_test", str(_SCRIPT))
assert _spec and _spec.loader
rl = importlib.util.module_from_spec(_spec)
sys.modules["recompile_locks_under_test"] = rl
_spec.loader.exec_module(rl)

# 真实形状的两份锁片段（含 pip-tools 的横幅与 via 注记）。
_LOCK_A = """\
#
# This file is autogenerated by pip-compile with Python 3.13
# by the following command:
#
#    pip-compile --output-file=requirements.lock requirements.txt
#

aiohttp==3.14.4
    # via
    #   aiohttp-retry
    #   kubernetes
mcp==1.2.3
    # via -r requirements-mcp.txt
"""

_LOCK_B = """\
#
# This file is autogenerated by pip-compile with Python 3.13
# by the following command:
#
#    pip-compile --output-file=requirements.lock requirements.txt
#
#    (上面那行不重要)

aiohttp==3.14.4
    # via
    #   aiohttp-retry
    #   kubernetes
mcp==1.2.3
    # via -r requirements-mcp.txt
"""


def test_横幅不同而pin相同_不算变化() -> None:
    """注释横幅的措辞/空行差异不许被读成"依赖更新了"（按字节比就会）。"""
    assert rl._structural(_LOCK_A) == rl._structural(_LOCK_B)
    assert rl.diff_summary(_LOCK_A, _LOCK_B) == []


def test_镜像源行被剔除出比较_且不算变化() -> None:
    """本机 pip.ini 漏进锁的 `--index-url/--trusted-host` 不是依赖信息（CONTRIBUTING 8.2）。

    它出现在一份里、另一份被人工删掉，判据必须说"没变化" —— 否则第一周那张 PR 的
    全部内容就是删两行配置残留，而 PR 的标题写的是"依赖更新"。
    """
    polluted = (
        _LOCK_A
        + "--index-url https://pypi.tuna.tsinghua.edu.cn/simple\n"
        + "--trusted-host pypi.tuna.tsinghua.edu.cn\n"
    )
    assert rl._structural(polluted) == rl._structural(_LOCK_A)


def test_任何一条pin动了都要报() -> None:
    changed = _LOCK_A.replace("mcp==1.2.3", "mcp==1.2.4")
    summary = rl.diff_summary(_LOCK_A, changed)
    assert summary == ["changed mcp: 1.2.3 -> 1.2.4"], summary


def test_新增与删除各自点名() -> None:
    added = _LOCK_A + "newpkg==1.0.0\n    # via mcp\n"
    assert rl.diff_summary(_LOCK_A, added) == ["added   newpkg==1.0.0"]
    removed = _LOCK_A.replace("mcp==1.2.3\n    # via -r requirements-mcp.txt\n", "")
    assert rl.diff_summary(_LOCK_A, removed) == ["removed mcp==1.2.3"]


def test_pin没变而via注记变了_仍算变化但降级表述() -> None:
    """依赖图变了（谁引入这条包变了）而版本没变 —— 不能因为"pin 集合相同"就闭嘴。"""
    annotate = _LOCK_A.replace("    # via -r requirements-mcp.txt", "    # via kubernetes")
    assert rl.diff_summary(_LOCK_A, annotate) == ["changed (annotations only)"]


def test_pin按PEP503口径归一比对() -> None:
    """`_pins` 把包名归一成小写再比：大小写写法不同不该算"新增+删除"两条。"""
    pins = rl._pins("AioHttp==3.14.4\nmcp==1.2.3\n")
    assert set(pins) == {"aiohttp", "mcp"}
    # 结构行仍然照原样参与比较（归一只用于"是谁"的判定，不改写锁的内容）
    assert "AioHttp==3.14.4" in rl._structural("AioHttp==3.14.4\n")


def test_刷不了必须退2_不许退成0(monkeypatch) -> None:
    """**fail-closed 的那一档**：pip-compile 跑不动 ⇒ 退出码 2，不是 0。

    "刷不了"报成"没变化"，那一周就安静地没有依赖更新而没人知道 —— 与 audit_deps /
    scan_secrets 同一条判据（扫不成 ≠ 干净）。离线可控：把 `_compile` 换成返回 None，
    不真出网。
    """
    monkeypatch.setattr(rl, "_compile", lambda *a, **k: None)
    monkeypatch.setattr(sys, "argv", ["recompile_locks.py", "--check"])
    assert rl.main() == 2


def test_锁文件不见了也退2(monkeypatch, tmp_path: Path) -> None:
    """缺锁不猜、不静默跳过：当红（2）。"""
    monkeypatch.setattr(rl, "LOCK_SURFACES", {"requirements.lock": ("requirements.txt",)})
    monkeypatch.setattr(rl, "ROOT", tmp_path)  # 空目录里没有任何锁
    monkeypatch.setattr(sys, "argv", ["recompile_locks.py"])
    assert rl.main() == 2


def test_compile中途崩不许留下被截断的锁(monkeypatch, tmp_path: Path) -> None:
    """**pip-tools 是直接覆写目标文件的**（`writer.py` 开 `dst` 写，没有临时文件改名），

    所以"解析跑到一半崩"会在工作树里留下一份截断的锁。调用方此时只会退 2 喊红 ——
    红得对，但锁已经坏了，而下一个坏锁现场是"pip install 装不上"，没人会想到是上周
    那次红弄的。这里钉的是：失败之后磁盘上的字节必须与进入前**完全相同**。
    """
    lock = tmp_path / "requirements.lock"
    original = _LOCK_A.encode("utf-8")
    lock.write_bytes(original)
    monkeypatch.setattr(rl, "ROOT", tmp_path)
    monkeypatch.setattr(rl, "LOCK_SURFACES", {"requirements.lock": ("requirements.txt",)})

    def explode(*_a, **_k):
        # 模拟"已经开了写句柄、写了一半"再崩：文件被清空/截断，异常照抛
        lock.write_bytes(original[:40])
        raise OSError("resolver died mid-write")

    # 让 `shutil.which` 报"找得到 pip-compile"，跳过开头那次可用性探测 ——
    # 不然这个 run 替身会先被探测步吃掉（那也测到了东西，但测的不是本格要钉的善后）。
    monkeypatch.setattr(rl.shutil, "which", lambda _name: "/usr/bin/pip-compile")
    monkeypatch.setattr(rl.subprocess, "run", explode)
    monkeypatch.setattr(sys, "argv", ["recompile_locks.py"])
    assert rl.main() == 2
    assert lock.read_bytes() == original, "失败路径把截断的锁留在了工作树里"


def test_探测步自己崩了也必须退2(monkeypatch) -> None:
    """开头那次"pip-tools 在不在"的探测不许抛穿 `main()`。

    抛穿的退出码是 1，而 **1 在调用方契约里 = "锁变了"** —— CI 会拿一次根本没跑成的
    解析去开 PR。这是本工具最坏的一种失效：不是不工作，是工作失败时看起来像成功。
    """
    def boom(*_a, **_k):
        raise OSError("no exe")

    monkeypatch.setattr(rl.shutil, "which", lambda _name: None)
    monkeypatch.setattr(rl.subprocess, "run", boom)
    monkeypatch.setattr(sys, "argv", ["recompile_locks.py"])
    assert rl.main() == 2
